<a href="https://colab.research.google.com/github/sierracthomas/misc_projects/blob/master/weightingfunctionmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import re

Change filename to match yours

change `text_file_length` (find yours by doing `wc -l <text file name> on terminal`)



In [27]:
file1 = open('538_list_4_coin_type.txt', 'r')
count = 0
line = 0
coin_jar = []

text_file_length = 23089

lines = file1.readlines()

for line in lines:
  split_line = line.split()
  coin_jar.append(split_line)
  count += 1

array = np.array(coin_jar)

np.reshape(array, (text_file_length, 8))

file1.close()


arr = (array[::1, ::2]).astype(int)
#print(arr)
#arr = arr[1]

final_values = []

m, n = text_file_length, 4
sum = 0
for i in range(0, m):
  for j in range(0, n):
    sum += arr[i][j]
  if sum == 58:
#    print(arr[i])
    weight = np.math.factorial(58)/(np.math.factorial(arr[i][1]) * np.math.factorial(arr[i][2]) * np.math.factorial(arr[i][3]) * np.math.factorial(arr[i][0]))
    print(weight)
    print(arr[i])
    final_values.append(weight)
  sum = 0

print(final_values)

print(max(final_values))
#print(sum)
#print(arr)


#print(array[1].sum())
#for l in array:
#  print(array.sum(axis=0))



809507160.0
[ 0 52  3  3]
43830765178200.0
[ 1 48  6  3]
2.03061673532718e+17
[ 2 44  9  3]
2348076705975.0
[ 2 48  0  8]
1.6706560753781817e+20
[ 3 40 12  3]
6.09185020598154e+17
[ 3 44  3  8]
3.355632059973891e+22
[ 4 36 15  3]
4.1348737865610004e+21
[ 4 40  6  8]
1.937877514634922e+24
[ 5 32 18  3]
3.598915384321998e+24
[ 5 36  9  8]
3.8553601739496504e+18
[ 5 40  0 13]
3.4930363622191376e+25
[ 6 28 21  3]
6.424063961014767e+26
[ 6 32 12  8]
2.3489424419817236e+23
[ 6 36  3 13]
2.0191959208480193e+26
[ 7 24 24  3]
2.9012162014202953e+28
[ 7 28 15  8]
3.953270129855241e+26
[ 7 32  6 13]
3.6676881803300945e+26
[ 8 20 27  3]
3.639853046818661e+29
[ 8 24 18  8]
8.461880587475862e+28
[ 8 28  9 13]
3.4604955618480753e+22
[ 8 32  0 18]
1.9452599051668646e+26
[ 9 16 30  3]
1.2924671169756087e+30
[ 9 20 21  8]
3.500141515728652e+30
[ 9 24 12 13]
5.530640906846968e+26
[ 9 28  3 18]
2.5955813983898045e+25
[10 12 33  3]
1.2375500359183447e+30
[10 16 24  8]
3.2696706590006726e+31
[10 20 15 13]
2

In [28]:
cents = 583
denominations = [25, 10, 5, 1]
names = {25: "quarter(s)", 10: "dime(s)", 5 : "nickel(s)", 1 : "pennies"}

def count_combs(left, i, comb, add):
    if add: comb.append(add)
    if left == 0 or (i+1) == len(denominations):
        if (i+1) == len(denominations) and left > 0:
           if left % denominations[i]:
               return 0
           comb.append( (left/denominations[i], demoninations[i]) )
           i += 1
        while i < len(denominations):
            comb.append( (0, denominations[i]) )
            i += 1
        print(" ".join("%d %s" % (n,names[c]) for (n,c) in comb))
        return 1
    cur = denominations[i]
    return sum(count_combs(left-x*cur, i+1, comb[:], (x,cur)) for x in range(0, int(left/cur)+1))

count_combs(cents, 0, [], None)


TypeError: ignored